// Generated by scripts/sdk-contract/generate-swift.py. Do not edit.
import Foundation

public struct Conversation: Sendable, Decodable, Hashable, Identifiable {
  public var acp: Bool?
  public var agentID: String?
  public var agentVersion: Int?
  public var agentVersionID: String?
  public var channelID: String?
  public var current: Bool?
  public var environmentID: String?
  public var firstPrompt: String?
  public var id: String
  public var insertedAt: Date?
  public var labels: [String: String]?
  public var lastActiveAt: Date?
  public var lastReadAt: Date?
  public var parentConversationID: String?
  public var pendingRequests: [PendingPermissionRequest]?
  public var permissionPolicyValues: [String: JSONValue]?
  public var runtime: Runtime
  public var runtimeSessionID: String?
  public var sandbox: Sandbox?
  public var sandboxAPIAccess: SandboxAPIAccess?
  public var sandboxID: String?
  public var source: ConversationSource?
  public var status: ConversationStatus
  public var title: String?
  public var turnCount: Int?
  public var unread: Bool?
  public var updatedAt: Date?
  public var usageTotal: Usage?
  public var vaultID: String?

  /// String verdicts for compatibility. Use permissionPolicyValues for numeric policy values.
  public var permissionPolicy: [String: String]? {
    get { permissionPolicyValues?.compactMapValues(\.stringValue) }
    set { permissionPolicyValues = newValue?.mapValues(JSONValue.string) }
  }

  enum CodingKeys: String, CodingKey {
    case acp = "acp"
    case agentID = "agent_id"
    case agentVersion = "agent_version"
    case agentVersionID = "agent_version_id"
    case channelID = "channel_id"
    case current = "current"
    case environmentID = "environment_id"
    case firstPrompt = "first_prompt"
    case id = "id"
    case insertedAt = "inserted_at"
    case labels = "labels"
    case lastActiveAt = "last_active_at"
    case lastReadAt = "last_read_at"
    case parentConversationID = "parent_conversation_id"
    case pendingRequests = "pending_requests"
    case permissionPolicyValues = "permission_policy"
    case runtime = "runtime"
    case runtimeSessionID = "runtime_session_id"
    case sandbox = "sandbox"
    case sandboxAPIAccess = "sandbox_api_access"
    case sandboxID = "sandbox_id"
    case source = "source"
    case status = "status"
    case title = "title"
    case turnCount = "turn_count"
    case unread = "unread"
    case updatedAt = "updated_at"
    case usageTotal = "usage_total"
    case vaultID = "vault_id"
  }
}

public struct Turn: Sendable, Decodable, Hashable, Identifiable {
  public var endedAt: Date?
  public var exitCode: Int?
  public var id: String
  public var imageCount: Int?
  public var insertedAt: Date?
  public var limitReason: String?
  public var modelSelection: TurnModelSelection?
  public var origin: TurnOrigin?
  public var prompt: String
  public var startedAt: Date?
  public var status: TurnStatus
  public var turnNumber: Int
  public var usage: Usage?
  public var waiting: Bool?

  enum CodingKeys: String, CodingKey {
    case endedAt = "ended_at"
    case exitCode = "exit_code"
    case id = "id"
    case imageCount = "image_count"
    case insertedAt = "inserted_at"
    case limitReason = "limit_reason"
    case modelSelection = "model_selection"
    case origin = "origin"
    case prompt = "prompt"
    case startedAt = "started_at"
    case status = "status"
    case turnNumber = "turn_number"
    case usage = "usage"
    case waiting = "waiting"
  }
}

public struct ConversationCreateRequest: Sendable, Encodable {
  public var agentID: String
  private var _channelID: ConversationInputField<String> = .omitted
  public var channelID: String? {
    get { _channelID.value }
    set { _channelID = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _environmentID: ConversationInputField<String> = .omitted
  public var environmentID: String? {
    get { _environmentID.value }
    set { _environmentID = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _fresh: ConversationInputField<Bool> = .omitted
  public var fresh: Bool? {
    get { _fresh.value }
    set { _fresh = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _images: ConversationInputField<[ImageInput]> = .omitted
  public var images: [ImageInput]? {
    get { _images.value }
    set { _images = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _inferenceCredentialID: ConversationInputField<String> = .omitted
  public var inferenceCredentialID: String? {
    get { _inferenceCredentialID.value }
    set { _inferenceCredentialID = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _labels: ConversationInputField<[String: String]> = .omitted
  public var labels: [String: String]? {
    get { _labels.value }
    set { _labels = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _permissionPolicyValues: ConversationInputField<[String: JSONValue]> = .omitted
  public var permissionPolicyValues: [String: JSONValue]? {
    get { _permissionPolicyValues.value }
    set { _permissionPolicyValues = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _prompt: ConversationInputField<String> = .omitted
  public var prompt: String? {
    get { _prompt.value }
    set { _prompt = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _queue: ConversationInputField<Bool> = .omitted
  public var queue: Bool? {
    get { _queue.value }
    set { _queue = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _sandboxAPIAccess: ConversationInputField<SandboxAPIAccess> = .omitted
  public var sandboxAPIAccess: SandboxAPIAccess? {
    get { _sandboxAPIAccess.value }
    set { _sandboxAPIAccess = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _sandboxID: ConversationInputField<String> = .omitted
  public var sandboxID: String? {
    get { _sandboxID.value }
    set { _sandboxID = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _sandboxMode: ConversationInputField<SandboxMode> = .omitted
  public var sandboxMode: SandboxMode? {
    get { _sandboxMode.value }
    set { _sandboxMode = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _spriteName: ConversationInputField<String> = .omitted
  public var spriteName: String? {
    get { _spriteName.value }
    set { _spriteName = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _title: ConversationInputField<String> = .omitted
  public var title: String? {
    get { _title.value }
    set { _title = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _vaultID: ConversationInputField<String> = .omitted
  public var vaultID: String? {
    get { _vaultID.value }
    set { _vaultID = newValue.map(ConversationInputField.value) ?? .omitted }
  }

  /// String verdicts for compatibility. Use permissionPolicyValues for numeric policy values.
  public var permissionPolicy: [String: String]? {
    get { permissionPolicyValues?.compactMapValues(\.stringValue) }
    set { permissionPolicyValues = newValue?.mapValues(JSONValue.string) }
  }

  public init(
    agentID: String,
    prompt: String? = nil,
    title: String? = nil,
    vaultID: String? = nil,
    environmentID: String? = nil,
    permissionPolicy: [String: String]? = nil,
    images: [ImageInput]? = nil,
    spriteName: String? = nil,
    sandboxMode: SandboxMode? = nil,
    sandboxAPIAccess: SandboxAPIAccess? = nil,
    sandboxID: String? = nil,
    channelID: String? = nil,
    fresh: Bool? = nil,
    inferenceCredentialID: String? = nil,
    labels: [String: String]? = nil,
    queue: Bool? = nil
  ) {
    self.agentID = agentID
    self.prompt = prompt
    self.title = title
    self.vaultID = vaultID
    self.environmentID = environmentID
    self.permissionPolicyValues = permissionPolicy?.mapValues(JSONValue.string)
    self.images = images
    self.spriteName = spriteName
    self.sandboxMode = sandboxMode
    self.sandboxAPIAccess = sandboxAPIAccess
    self.sandboxID = sandboxID
    self.channelID = channelID
    self.fresh = fresh
    self.inferenceCredentialID = inferenceCredentialID
    self.labels = labels
    self.queue = queue
  }

  enum CodingKeys: String, CodingKey {
    case agentID = "agent_id"
    case channelID = "channel_id"
    case environmentID = "environment_id"
    case fresh = "fresh"
    case images = "images"
    case inferenceCredentialID = "inference_credential_id"
    case labels = "labels"
    case permissionPolicyValues = "permission_policy"
    case prompt = "prompt"
    case queue = "queue"
    case sandboxAPIAccess = "sandbox_api_access"
    case sandboxID = "sandbox_id"
    case sandboxMode = "sandbox_mode"
    case spriteName = "sprite_name"
    case title = "title"
    case vaultID = "vault_id"
  }

  /// Fields for which the API accepts an explicit JSON null.
  public enum NullableField: Sendable {
    case channelID
    case environmentID
    case fresh
    case images
    case inferenceCredentialID
    case labels
    case permissionPolicyValues
    case queue
    case sandboxID
    case sandboxMode
    case title
    case vaultID
  }

  /// Send null. Assigning the property nil again restores omission.
  public mutating func setNull(_ field: NullableField) {
    switch field {
    case .channelID: _channelID = .null
    case .environmentID: _environmentID = .null
    case .fresh: _fresh = .null
    case .images: _images = .null
    case .inferenceCredentialID: _inferenceCredentialID = .null
    case .labels: _labels = .null
    case .permissionPolicyValues: _permissionPolicyValues = .null
    case .queue: _queue = .null
    case .sandboxID: _sandboxID = .null
    case .sandboxMode: _sandboxMode = .null
    case .title: _title = .null
    case .vaultID: _vaultID = .null
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(agentID, forKey: .agentID)
    try _channelID.encode(into: &container, forKey: .channelID)
    try _environmentID.encode(into: &container, forKey: .environmentID)
    try _fresh.encode(into: &container, forKey: .fresh)
    try _images.encode(into: &container, forKey: .images)
    try _inferenceCredentialID.encode(into: &container, forKey: .inferenceCredentialID)
    try _labels.encode(into: &container, forKey: .labels)
    try _permissionPolicyValues.encode(into: &container, forKey: .permissionPolicyValues)
    try _prompt.encode(into: &container, forKey: .prompt)
    try _queue.encode(into: &container, forKey: .queue)
    try _sandboxAPIAccess.encode(into: &container, forKey: .sandboxAPIAccess)
    try _sandboxID.encode(into: &container, forKey: .sandboxID)
    try _sandboxMode.encode(into: &container, forKey: .sandboxMode)
    try _spriteName.encode(into: &container, forKey: .spriteName)
    try _title.encode(into: &container, forKey: .title)
    try _vaultID.encode(into: &container, forKey: .vaultID)
  }
}

public struct ImageInput: Sendable, Encodable {
  public var data: String
  public var mediaType: String

  public init(
    data: String,
    mediaType: String
  ) {
    self.data = data
    self.mediaType = mediaType
  }

  enum CodingKeys: String, CodingKey {
    case data = "data"
    case mediaType = "media_type"
  }
}

public struct Usage: Sendable, Decodable, Hashable {
  public var accounting: UsageAccounting?
  public var cacheRead: Int?
  public var cacheWrite: Int?
  public var input: Int?
  public var output: Int?

  enum CodingKeys: String, CodingKey {
    case accounting = "accounting"
    case cacheRead = "cache_read"
    case cacheWrite = "cache_write"
    case input = "input"
    case output = "output"
  }
}

public struct UsageAccounting: Sendable, Decodable, Hashable {
  public var completeness: String
  public var scope: String
  public var source: String
  public var version: Int

  enum CodingKeys: String, CodingKey {
    case completeness = "completeness"
    case scope = "scope"
    case source = "source"
    case version = "version"
  }
}

public struct PendingPermissionRequest: Sendable, Decodable, Hashable {
  public var askedAt: Date?
  public var deadline: Date?
  public var options: [[String: JSONValue]]
  public var requestID: String
  public var tool: String?
  public var turnID: String?

  enum CodingKeys: String, CodingKey {
    case askedAt = "asked_at"
    case deadline = "deadline"
    case options = "options"
    case requestID = "request_id"
    case tool = "tool"
    case turnID = "turn_id"
  }
}

public struct TurnModelSelection: Sendable, Decodable, Hashable {
  public var effectiveModel: String?
  public var error: String?
  public var requestedModel: String?
  public var source: String?
  public var status: String?

  enum CodingKeys: String, CodingKey {
    case effectiveModel = "effective_model"
    case error = "error"
    case requestedModel = "requested_model"
    case source = "source"
    case status = "status"
  }
}
